import type { Metadata } from "next"
import { CodeBlock } from "@/components/site/code-block"
import { DocsShell } from "@/components/site/docs-shell"
import { registryItems } from "@/content/registry-items"

export const metadata: Metadata = { title: "Installation", description: "Install components from the AwwwardWinning UI registry." }
const command = registryItems[0].installCommand

export default function InstallationPage() {
  return <DocsShell active="installation"><main className="min-w-0 max-w-3xl px-5 py-10 sm:px-10 sm:py-12"><p className="text-sm text-muted-foreground">Documentation</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Installation</h1><p className="mt-3 text-sm leading-6 text-muted-foreground">Registry components are copied into your project. You own and adapt their source.</p><div className="mt-10 space-y-9"><section><h2 className="text-lg font-semibold">Requirements</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Use a Next.js or React project with Tailwind CSS, TypeScript, and pnpm. The project must have shadcn initialized.</p></section><section><h2 className="text-lg font-semibold">1. Initialize shadcn</h2><div className="mt-3"><CodeBlock code="pnpm dlx shadcn@latest init" label="Copy command" /></div></section><section><h2 className="text-lg font-semibold">2. Install a registry component</h2><div className="mt-3"><CodeBlock code={command} label="Copy command" /></div><p className="mt-2 text-sm leading-6 text-muted-foreground">The CLI downloads the registry definition, installs declared packages, and adds the component to the target set in the registry.</p></section><section><h2 className="text-lg font-semibold">What is added?</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">The selected component is added to your configured <code className="rounded bg-muted px-1 py-0.5 text-xs">components/ui</code> directory. Neither current component requires an additional package.</p></section><section><h2 className="text-lg font-semibold">Source ownership and removal</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">After installation the component is ordinary project source. Modify it freely. To remove it, delete its installed file and uninstall any dependency no longer used elsewhere.</p></section><section><h2 className="text-lg font-semibold">Troubleshooting</h2><ul className="mt-2 list-disc space-y-2 pl-5 text-sm leading-6 text-muted-foreground"><li>Run the command from the app root containing <code>components.json</code>.</li><li>Ensure the registry URL is reachable; use your deployed URL outside local development.</li><li>If aliases differ, confirm the shadcn configuration points to a valid <code>lib/utils.ts</code> utility.</li></ul></section></div></main></DocsShell>
}
